config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :blocked_dates

  mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  namespace :api do
    namespace :v1 do
      post 'get-user-blocked-dates', to: 'synchronization#get_user_blocked_dates'
      post 'send-user-blocked-dates', to:  'synchronization#send_user_blocked_dates'
      post 'destroy-user-blocked-dates', to:  'synchronization#destroy_user_blocked_dates'
    end
  end

  devise_for :users

  root to: 'blocked_dates#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blocked_date.rb
class BlockedDate < ApplicationRecord
  belongs_to :user

  validates :starting_date, presence: true
  validates :ending_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if ending_date.blank? || starting_date.blank?

    if ending_date < starting_date
      errors.add(:ending_date, "cannot be before the starting date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :validatable

  after_create :sync_blocked_dates
  has_many :blocked_dates

  private

  def sync_blocked_dates
    SynchronizationService::GetBlockedDates.run(user_id: id, user_email: email)
  end
end

app/controllers/api/v1/api_base_controller.rb
module Api
  module V1
    class ApiBaseController < ApplicationController
      private

      def request_token
        request.headers['Authorization'].try(:gsub, /^Bearer /, '')
      end

      def validate_token
        valid = AuthTokenService::AuthTokenValidate.run(token: request_token)

        render json: { message: 'Invalid token' }, status: :unprocessable_entity unless valid
      end
    end
  end
end

app/controllers/api/v1/synchronization_controller.rb
module Api
  module V1
    class SynchronizationController < ApiBaseController
      before_action :validate_token

      def get_user_blocked_dates
        user = get_user

        if user.present?
          render json: {
            blocked_dates: user.blocked_dates.select(:id, :starting_date, :ending_date)
          }
        else
          render json: { message: 'Invalid token' }, status: :unprocessable_entity
        end
      end

      def send_user_blocked_dates
        user = get_user
        StoreBlockedDateWorker.perform_async(blocked_dates_params.to_h, user.id)

        render json: {}, status: :ok
      end

      def destroy_user_blocked_dates
        user = get_user
        DestroyBlockedDateWorker.perform_async(blocked_dates_params.to_h, user.id)
      end

      private

      def blocked_dates_params
        params.permit(:email, blocked_dates: [:id, :starting_date, :ending_date])
      end

      def get_user
        User.find_by(email: blocked_dates_params[:email])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/blocked_dates_controller.rb
class BlockedDatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blocked_date, only: %i[ show edit update destroy ]

  # GET /blocked_dates or /blocked_dates.json
  def index
    @blocked_dates = current_user.blocked_dates
  end

  # GET /blocked_dates/1 or /blocked_dates/1.json
  def show
  end

  # GET /blocked_dates/new
  def new
    @blocked_date = BlockedDate.new
    @formatted_blocked_dates = BlockedDateService::FormattedBlockedDatesList.run(blocked_dates: current_user.blocked_dates)
  end

  # GET /blocked_dates/1/edit
  def edit
  end

  # POST /blocked_dates or /blocked_dates.json
  def create
    @blocked_date = BlockedDate.new(BlockedDateService::SplitDate.run(params: blocked_date_params))

    respond_to do |format|
      if @blocked_date.save
        send_blocked_date(true)
        format.html { redirect_to blocked_dates_path, notice: "Blocked date was successfully created." }
        format.json { render :show, status: :created, location: @blocked_date }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blocked_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocked_dates/1 or /blocked_dates/1.json
  def update
    respond_to do |format|
      if @blocked_date.update(blocked_date_params)
        format.html { redirect_to blocked_date_url(@blocked_date), notice: "Blocked date was successfully updated." }
        format.json { render :show, status: :ok, location: @blocked_date }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blocked_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocked_dates/1 or /blocked_dates/1.json
  def destroy
    @blocked_date.destroy
    send_blocked_date(false)

    respond_to do |format|
      format.html { redirect_to blocked_dates_url, notice: "Blocked date was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blocked_date
    @blocked_date = BlockedDate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blocked_date_params
    permitted_params = params.fetch(:blocked_date, {}).permit(:date_range, :user_id)
  end

  def send_blocked_date(create)
    SendBlockedDateWorker.perform_async(
      [{
         id: @blocked_date.id,
         starting_date: @blocked_date.starting_date,
         ending_date: @blocked_date.ending_date
       }],
      current_user.email,
      create
    )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @date = BlockedDate.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocked_dates_helper.rb
module BlockedDatesHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blocked_dates/_form.html.erb
<%= form_with(model: blocked_date) do |form| %>
  <% if blocked_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blocked_date.errors.count, "error") %> prohibited this blocked_date from being saved:</h2>

      <ul>
        <% blocked_date.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :date_range, class: 'invisible', data: { behavior: "flatpickr" } %>
  </div>


  <div class="field">
    <%= form.hidden_field :user_id, class: 'form-control', value: "#{current_user.id}" %>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="field mt-4">
        <%= form.submit 'Save', class: 'btn btn-success btn-block' %>
      </div>
    </div>
  </div>

<% end %>

<script>
    document.addEventListener("turbolinks:load", () => {
        flatpickr("[data-behavior='flatpickr']", {
            altInput: true,
            inline: true,
            altFormat: "F j, Y",
            dateFormat: "d-m-Y",
            mode: "range",
            minDate: "today",
            disable: <%= raw @formatted_blocked_dates.to_json %>,
        })
    })
</script>

app/views/blocked_dates/edit.html.erb
<h1>Editing Blocked Date</h1>

<%= render 'form', blocked_date: @blocked_date %>

<%= link_to 'Show', @blocked_date %> |
<%= link_to 'Back', blocked_dates_path %>

app/views/blocked_dates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blocked Dates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Starting</th>
      <th>Ending</th>
      <th colspan="3" class="w-25"></th>
    </tr>
  </thead>

  <tbody>
    <% @blocked_dates.each do |blocked_date| %>
      <tr>
        <td><%= blocked_date.starting_date.strftime("%d-%m-%Y") %></td>
        <td><%= blocked_date.ending_date.strftime("%d-%m-%Y") %></td>
<!--        <td><%#= link_to 'Show', blocked_date, class: 'btn btn-light' %></td>-->
<!--        <td><%#= link_to 'Edit', edit_blocked_date_path(blocked_date), class: 'btn btn-light' %></td>-->
        <td><%= link_to 'Destroy', blocked_date, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
  <div class="col-md-2">
    <%= link_to 'New Blocked Date', new_blocked_date_path, class: 'btn btn-primary btn-block' %>
  </div>
</div>
<div class="row">
  <div class="col-md-2 mt-2">
    <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn btn-danger btn-block' %>
  </div>
</div>

app/views/blocked_dates/new.html.erb
<div class="row d-flex justify-content-center">
  <div class="row">
    <div class="col-md-6 offset-5">
      <h1>New Blocked Date</h1>

      <%= render 'form', blocked_date: @blocked_date %>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-md-2">
      <div class="field mt-4">
        <%= link_to 'Back', blocked_dates_path, class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/blocked_dates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blocked_date_path(@blocked_date) %> |
<%= link_to 'Back', blocked_dates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>